### PR TITLE
Add `showSystemCursorOnClickable` parameter to show system cursor on clickables

### LINKED ISSUE #39: System cursor not shown on clickables with `showSystemCursor` = `true`

### PR DESCRIPTION
**Pull request by Favo02**
fixes #39 

- fixed typo in readme
- added `showSystemCursorOnClickable` parameter
- added docs for `showSystemCursorOnClickable`

### CODE REVIEW

**Review by stephenscaff — COMMENTED** [review]
First - thanks. You caught what i missed.


I figured it might be good to offer the default browser cursor as an option for people that might be nervous about killing it completely. 

Second - should we make this available as a seperate prop?
Or should we roll it all into the same prop / option?

If you want the cursor, you probs want it everywhere right?
So, should `showSystemCursor` just be used to handle the checks you added with `showSystemCursorOnClickable`?

Or.... is there a good reason to keep them separate?

Let me know what you think.

Thanks again.

**Comment by Favo02** [comment]
Thank you for developing this amazing and super useful package! I'm just trying to be helpful.

I think that if someone wants to show the system cursor he probably wants it always visible (also on clickables elements), this is my use case.

But because the package already implemented a way to show cursor (but only outside of clickables) I thought this was intended behaviour so I added an additional parameter to keep them separate (you never know what people wants).

More customization is better than less customization, so I think it is not a bad idea to keep both parameters as they are both really simple to understand and utilize.

Another way could be to always show the cursor with `showSystemCursor` = `true` and add an additional parameter such as `hideSystemCursorOnClickable` (that should be used only with `showSystemCursor` = `true`) to hide the cursor only on clickables. The advantage of this solution is one less parameter for the most obvious use case (always show the cursor), but "harder" to understand and to enforce a correct parameter usage.

In the end I would keep them separate to give the maximum personalization in the easiest way, but the decision is yours. Let me know what is your final decision.

**Comment by Favo02** [comment]
@stephenscaff sorry for the tag, any update on this?

**Comment by stephenscaff** [comment]
Migrated to TS and rolled maintained a single option for clickables and all up page.
Thanks for your thoughts though. Appreciate you taking the time to help out.

**Pull request closed without merging**
