### PR TITLE
TS conversion proposal

### PR DESCRIPTION
**Pull request by Thremulant**
Hi Stephen, 

First, thank you for the library, I really liked it! I just couldn't implement it because of the missing types. 

Second, here's my proposal to change to TS. I'm no TS expert, so bear with me if I made some mistakes. There's always more strict typing that can be implemented. 

### Key Features 
1. TS components and strong typing (still a WIP) 
2. Rollup configuration to extract the Types
3. HEX and RGBA accepted in the property `color` 

I tested locally this `build` (using `yalc`) and it worked fine on a regular CRA project with no TS and one with TS. 

Hope this can help the project, and let me know if there's something that can be improved. 

Regards, 
Daniel

### CODE REVIEW

**Comment by stephenscaff** [comment]
Hi @Thremulant.

Nice! This has been on my todo list as well, so appreciate you diving in. I'm no TS expert myself, but using this lib in enough TS projects that it's an issue. 

Will check it out.

**Comment by stephenscaff** [comment]
@Thremulant My bad bud, been hectic at work. I'll finish reviewing this tomorrow. Looks good.... just wanna test it a bit.

**Comment by gayuru** [comment]
Hey @stephenscaff how's this going? would like an update please -- @Thremulant solution is looking fine

**Review by Wiz-Amit — APPROVED** [review]

**Comment by Thremulant** [comment]
Hey @stephenscaff  any news on this one?

**Comment by Thremulant** [comment]
Hey @stephenscaff is anything I can help you here, to merge this one?

**Comment by stephenscaff** [comment]
Migrated to TS a while back, closing this one. Thanks for the help.

**Pull request closed without merging**
